<a href="https://colab.research.google.com/github/eliba12/Deep-Learning-GEN/blob/main%2FDeep-Learning-%26-GEN/Pre_trained_Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using Pre_trained Transformer Model (Cardiff NLP):


Using Pretrained model which review X comments, applying to analysise Restaurant reviews

In [1]:
from transformers import AutoTokenizer

In [2]:
MODEL = f"cardiffnlp/twitter-roberta-base-sentiment-latest"
tokenizer = AutoTokenizer.from_pretrained(MODEL)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/929 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [3]:
from transformers import pipeline
sentiment_task = pipeline("sentiment-analysis", model=MODEL, tokenizer=tokenizer)

pytorch_model.bin:   0%|          | 0.00/501M [00:00<?, ?B/s]

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [5]:
#Create a table of reviews
import pandas as pd

# Define review data as a list of dictionaries
data = [
    {"Restaurant": "Little Italy", "Rating": 5, "Review": "Delicious food, great service!"},
    {"Restaurant": "Burger Barn", "Rating": 3, "Review": "Average burger, slow service."},
    {"Restaurant": "Spicy Curry", "Rating": 4, "Review": "Excellent curry, a bit pricey."},
    {"Restaurant": "The French Bistro", "Rating": 1, "Rating": "Waited an hour for food, never came."},
    {"Restaurant": "Cozy Cafe", "Rating": 4, "Review": "Nice atmosphere, coffee a bit weak."},
    {"Restaurant": "Yum Yum Noodles", "Rating": 5, "Review": "Fantastic noodles, friendly staff!"},
]

# Create a DataFrame from the data
df = pd.DataFrame(data)

df

,Restaurant,Rating,Review
0,Little Italy,5,"Delicious food, great service!"
1,Burger Barn,3,"Average burger, slow service."
2,Spicy Curry,4,"Excellent curry, a bit pricey."
3,The French Bistro,"Waited an hour for food, never came.",NaN
4,Cozy Cafe,4,"Nice atmosphere, coffee a bit weak."
5,Yum Yum Noodles,5,"Fantastic noodles, friendly staff!"

In [6]:
sentiment_task('I love Hugging face')

[{'label': 'positive', 'score': 0.943440318107605}]

In [7]:
df['Sentiment'] = 'NaN'

In [8]:
for i in range(len(df['Review'])):
  df['Sentiment'][i] = sentiment_task(str(df['Review'][i]))

<ipython-input-8-8a07b45911a6>:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Sentiment'][i] = sentiment_task(str(df['Review'][i]))
<ipython-input-8-8a07b45911a6>:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Sentiment'][i] = sentiment_task(str(df['Review'][i]))
<ipython-input-8-8a07b45911a6>:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Sentiment'][i] = sentiment_task(str(df['Review'][i]))
<ipython-input-8-8a07b45911a6>:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Sentiment'][i] = sentiment_task(str(df['Review'][i]))
<ipython-input-8-8a07b45911a6>:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Sentiment'][i] = sentiment_task(str(df['Review'][i]))
<ipython-input-8-8a07b45911a6>:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Sentiment'][i] = sentiment_task(str(df['Review'][i]))

In [9]:
df

,Restaurant,Rating,Review,Sentiment
0,Little Italy,5,"Delicious food, great service!","[{'label': 'positive', 'score': 0.982557952404..."
1,Burger Barn,3,"Average burger, slow service.","[{'label': 'negative', 'score': 0.910950899124..."
2,Spicy Curry,4,"Excellent curry, a bit pricey.","[{'label': 'positive', 'score': 0.944867134094..."
3,The French Bistro,"Waited an hour for food, never came.",NaN,"[{'label': 'neutral', 'score': 0.6808650493621..."
4,Cozy Cafe,4,"Nice atmosphere, coffee a bit weak.","[{'label': 'positive', 'score': 0.872350871562..."
5,Yum Yum Noodles,5,"Fantastic noodles, friendly staff!","[{'label': 'positive', 'score': 0.978859186172..."

In [10]:
df['label'] = df['Sentiment'].apply(lambda x:x[0]['label'])

In [11]:
df

,Restaurant,Rating,Review,Sentiment,label
0,Little Italy,5,"Delicious food, great service!","[{'label': 'positive', 'score': 0.982557952404...",positive
1,Burger Barn,3,"Average burger, slow service.","[{'label': 'negative', 'score': 0.910950899124...",negative
2,Spicy Curry,4,"Excellent curry, a bit pricey.","[{'label': 'positive', 'score': 0.944867134094...",positive
3,The French Bistro,"Waited an hour for food, never came.",NaN,"[{'label': 'neutral', 'score': 0.6808650493621...",neutral
4,Cozy Cafe,4,"Nice atmosphere, coffee a bit weak.","[{'label': 'positive', 'score': 0.872350871562...",positive
5,Yum Yum Noodles,5,"Fantastic noodles, friendly staff!","[{'label': 'positive', 'score': 0.978859186172...",positive